### ISSUE TITLE
Allow mocking of the E621Client to facilitate unit testing

### ISSUE THREAD

**Issue by GizmoCaritate** [NoppesTheFolf/E621Client#11]
I ran into an issue when using your package to interact with the E621 API. I wanted to unit test the code that makes use of the `E621Client`

I have no real code examples to show but it boils down to this:
Because of the builder / factory pattern the constructor of `E621Client` is set to `internal` because of which a mocking framework cannot create a mocked instance of the client.

It would be a possibility to solve this by creating a `IE621Client` interface that gets returned by the builder so that we can mock on that interface.

I will try to implement this and will link a PR to this issue when it's ready.

**Comment by NoppesTheFolf** [comment]
Thanks for bringing the issue to my attention! I did not anticipate this use case when I designed the library. Good luck ^^

**Comment by GizmoCaritate** [comment]
Change has been merged!
